name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Minecraft Image'
        run: |
          cd minecraft
          ./build-image 8  ghcr.io/${{github.actor}}/gameserver:mc-java-8
          ./build-image 16 ghcr.io/${{github.actor}}/gameserver:mc-java-16
          ./build-image 17 ghcr.io/${{github.actor}}/gameserver:mc-java-17
          ./build-image 21 ghcr.io/${{github.actor}}/gameserver:mc-java-21
